version: '3.8'

services:
  shell:
    image: karenkramekfiap/bytebank-shell:latest
    container_name: bytebank-shell
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - REACT_APP_DASHBOARD_URL=http://localhost:3031
      - REACT_APP_TRANSACTIONS_URL=http://localhost:3032
      - REACT_APP_INVESTMENTS_URL=http://localhost:3036
      - REACT_APP_SHARED_URL=http://localhost:3033
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - bytebank-network

  dashboard:
    image: karenkramekfiap/bytebank-dashboard:latest
    container_name: bytebank-dashboard
    ports:
      - "3031:3031"
    environment:
      - NODE_ENV=production
    networks:
      - bytebank-network

  transactions:
    image: karenkramekfiap/bytebank-transactions:latest
    container_name: bytebank-transactions
    ports:
      - "3032:3032"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3034
      - REACT_APP_UPLOAD_URL=http://localhost:3035
    networks:
      - bytebank-network

  shared:
    image: karenkramekfiap/bytebank-shared:latest
    container_name: bytebank-shared
    ports:
      - "3033:3033"
    environment:
      - NODE_ENV=production
    networks:
      - bytebank-network

  api:
    image: karenkramekfiap/bytebank-api:latest
    container_name: bytebank-api
    ports:
      - "3034:3034"
    volumes:
      - ./db.json:/data/db.json
    command: ["--watch", "/data/db.json", "--host", "0.0.0.0", "--port", "3034"]
    networks:
      - bytebank-network

  upload:
    image: karenkramekfiap/bytebank-upload:latest
    container_name: bytebank-upload
    ports:
      - "3035:3035"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - bytebank-network

  investments:
    image: karenkramekfiap/bytebank-investments:latest
    container_name: bytebank-investments
    ports:
      - "3036:3036"
    environment:
      - NODE_ENV=production
    networks:
      - bytebank-network

networks:
  bytebank-network:
    driver: bridge
