FROM node:22-alpine

WORKDIR /app

RUN npm install -g json-server@1.0.0-beta.3

COPY db.template.json /data/db.template.json

COPY docker/scripts/api-entrypoint.sh /usr/local/bin/api-entrypoint.sh

RUN chmod +x /usr/local/bin/api-entrypoint.sh

ENV PORT=3034

EXPOSE ${PORT}

CMD ["/usr/local/bin/api-entrypoint.sh"]
