version: '3.8'

services:
  api:
    image: karenkramekfiap/bytebank-api:latest
    container_name: bytebank-api
    ports:
      - "3034:3034"
    volumes:
      - ../db.json:/data/db.json
    environment:
      - PORT=3034
    restart: unless-stopped
    networks:
      - bytebank-network

  upload:
    image: karenkramekfiap/bytebank-upload:latest
    container_name: bytebank-upload
    ports:
      - "3035:3035"
    volumes:
      - ../uploads:/app/uploads
    restart: unless-stopped
    networks:
      - bytebank-network

networks:
  bytebank-network:
    driver: bridge
