name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'  # Qualquer branch que comece com feature/
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:  # Permite executar manualmente

env:
  DOCKER_USERNAME: karenkramekfiap

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          # Frontend services - Deploy no Vercel
          - name: shell
            context: shell
            dockerfile: docker/Dockerfile.frontend
            port: "3030"
            deploy_target: vercel
          - name: dashboard
            context: dashboard-mfe
            dockerfile: docker/Dockerfile.frontend
            port: "3031"
            deploy_target: vercel
          - name: transactions
            context: transactions-mfe
            dockerfile: docker/Dockerfile.frontend
            port: "3032"
            deploy_target: vercel
          - name: investments
            context: investments-mfe
            dockerfile: docker/Dockerfile.frontend
            port: "3036"
            deploy_target: vercel
          - name: shared
            context: shared
            dockerfile: docker/Dockerfile.frontend
            port: "3033"
            deploy_target: vercel
          # Backend services - Deploy na AWS EC2
          - name: api
            context: .
            dockerfile: docker/Dockerfile.jsonserver
            port: "3034"
            deploy_target: aws
          - name: upload
            context: upload-server
            dockerfile: docker/Dockerfile.node
            port: "3035"
            deploy_target: aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract branch name
        shell: bash
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          # Substituir / por - para ser válido como Docker tag
          BRANCH_NAME="${BRANCH_NAME//\//-}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Debug Docker Hub credentials
        run: |
          echo "Username: ${{ env.DOCKER_USERNAME }}"
          echo "Branch tag: ${{ env.BRANCH_NAME }}"
          echo "Token exists: ${{ secrets.DOCKER_HUB_TOKEN != '' }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          build-args: |
            PORT=${{ matrix.service.port }}
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/bytebank-${{ matrix.service.name }}:latest
            ${{ env.DOCKER_USERNAME }}/bytebank-${{ matrix.service.name }}:${{ env.BRANCH_NAME }}
            ${{ env.DOCKER_USERNAME }}/bytebank-${{ matrix.service.name }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/bytebank-${{ matrix.service.name }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_USERNAME }}/bytebank-${{ matrix.service.name }}:buildcache,mode=max
          labels: |
            deploy.target=${{ matrix.service.deploy_target }}
            service.name=${{ matrix.service.name }}
            service.port=${{ matrix.service.port }}

      - name: Image digest
        run: |
          echo "Image pushed - ${{ env.DOCKER_USERNAME }}/bytebank-${{ matrix.service.name }}:latest"
          echo "Deploy target: ${{ matrix.service.deploy_target }}"
          echo "📦 Frontend images (shell, dashboard, transactions, shared) = Deploy no Vercel"
          echo "🚀 Backend images (api, upload) = Deploy na AWS EC2"
